apiVersion: foogroup.raker22.com/v1
kind: FooReplicaSet
metadata:
  name: example-foo-replica-set
  labels:
    app: example
spec:
  replicas: 3
  template:
    message: hello world
    value: 42
  selector:
    matchLabels:
      app: example