apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: fooreplicasets.foo.raker22.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.currentReplicas
    name: Current Replicas
    type: integer
  - JSONPath: .spec.replicas
    name: Desired Replicas
    type: integer
  - JSONPath: .spec.template.spec.message
    name: Message
    type: string
  - JSONPath: .spec.template.spec.value
    name: Value
    type: integer
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: foo.raker22.com
  names:
    categories:
    - all
    - allfoo
    kind: FooReplicaSet
    plural: fooreplicasets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            replicas:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              format: int64
              minimum: 1
              type: integer
            selector:
              type: object
            template:
              properties:
                metadata:
                  type: object
                spec:
                  properties:
                    message:
                      description: 'INSERT ADDITIONAL SPEC FIELDS - desired state
                        of cluster Important: Run "make" to regenerate code after
                        modifying this file'
                      type: string
                    value:
                      format: int32
                      type: integer
                  required:
                  - message
                  - value
                  type: object
              required:
              - spec
              type: object
          required:
          - replicas
          - template
          - selector
          type: object
        status:
          properties:
            currentReplicas:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              format: int64
              type: integer
          required:
          - currentReplicas
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
